### ISSUE TITLE
Error: Class 'CRM_Iats_FapsRequest' not found in CRM_Core_Payment_Faps->doDirectPayment()

### ISSUE THREAD

**Issue by rocxa** [iATSPayments/com.iatspayments.civicrm#311] opened 2020-06-15 12:29 UTC
CiviCRM 5.24.6
Drupal 7.70

Steps:
- Enabled the iATS extension included with CiviCRM Core
- Created an iATS 1stPay Credit Card payment processor
- Created a contribution page
- Chose this payment processor
- Used the contribution page up to the point of confirming the payment details entered.
- Presented with this error

Error: Class 'CRM_Iats_FapsRequest' not found in CRM_Core_Payment_Faps->doDirectPayment() (line 340 of ***/iatspayments/CRM/Core/Payment/Faps.php).

I couldn't see anyone else reporting this issue

**Comment by KarinG** [comment] 2020-06-15 14:30
This is on our CiviCRM 5.24.6 test site -> do you see green bars after entering the credit card details but before you hit Confirm Contribution?

![image](https://user-images.githubusercontent.com/5340555/84669326-f8025b00-aee1-11ea-839e-a3e5037dea62.png)

**Comment by KarinG** [comment] 2020-06-15 14:32
Is it possible that you have another (older) copy of the iATS extension in another extensions directory?

**Comment by rocxa** [comment] 2020-06-15 15:22
Yes, green bars are visible. It is on confirming the payment the error appears.

It does seem like the extension is looking for files in the wrong place. Even though another version of extension is not installed.

"/civicrm/iATSAdmin" link is looking for 

> Error: Class 'CRM_Iats_Page_iATSAdmin' not found in CRM_Core_Invoke::runItem() (line 305 

but in the custom extensions directory rather than the core extension directory.

Perhaps to fix this I need to know where / how the extension is deciding which extension directory to get the class files from? it appears to be getting it wrong.

**Comment by KarinG** [comment] 2020-06-15 16:10
The Extension itself is not deciding where to look. CiviCRM core will find Extensions for you -> and will look in a number of places. What are your 

Extension Resource URL
Extensions Directory

And when you're in your Extensions screen -> what's the Local path [click on the black triangle before the Extension name

**Comment by rocxa** [comment] 2020-06-15 17:19
Local path for iATS Payments extension is:
*sitefolder*/modules/contrib/civicrm/ext/iatspayments

Extension resource URL is: 
https://*site*/civicrm_ext/extensions/

Extensions directory path is:
*sitefolder*/civicrm_ext/extensions/

The extension directories and urls we have set work for other extension such as mosaico/extendedreport

iATS is the only extension we are trying to use that is in the core civicrm folder structure.

Perhaps the location of the civicrm module isn't one of the places the code looks for e.g. it may not be expecting the 'contrib' folder..

**Comment by adixon** [comment] 2020-06-15 17:26
Yeah, that's an interesting hypothesis. According to the documentation here:
https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#suggested-directory-location
[haha, which I wrote a few years ago w/ some input from the core team], it should be finding the extension based on it's location inside the module folder (sitefolder/modules/contrib/civicrm).

We do have a lot of drupal 7.70 w/ 5.24.6 civicrm, but it's possible that none of them are actually using the core supplied version of civicrm ....

Alternatively, is it possible it's just a caching issue? Did you try the option here? /civicrm/admin/setting/updateConfigBackend?reset=1

**Comment by KarinG** [comment] 2020-06-15 17:41
Ok - here is a vanilla 5.25.0 -> iATS -> is shipped with - and located in -> **/files/civicrm/ext**

![image](https://user-images.githubusercontent.com/5340555/84688492-aa471c00-aefc-11ea-88f4-73b0f498359c.png)

**Comment by adixon** [comment] 2020-06-15 17:47
I've reread your issue and now see that it's finding stuff from that extension previously (e.g. CRM/Core/Payment/Faps.php), the issue seems to be specific to finding a couple of iats-specific classes (i.e. in CRM/Iats). I notice that both of the ones that are failing are using camel case filenames, I wonder if that's now causing an issue w/ the newest civi core? Let me check w/ someone more knowledgeable ...

**Comment by rocxa** [comment] 2020-06-15 18:18
> Ok - here is a vanilla 5.25.0 -> iATS -> is shipped with - and located in -> **/files/civicrm/ext**
> 
> ![image](https://user-images.githubusercontent.com/5340555/84688492-aa471c00-aefc-11ea-88f4-73b0f498359c.png)

CiviCRM 5.26.1 (latest) and 5.24.1 have the directory as civicrm/ext/iatspayments in the download.

**Comment by rocxa** [comment] 2020-06-15 18:29
I tried deleting the iatspayment files I had, and put back the ones from the latest civicrm.  Same issue occurs there.

**Comment by KarinG** [comment] 2020-06-15 18:30
ok my 5.25.0 above is a Drupal 8 so may yet have a different Extensions path! I'm going to try and run some more tests here to see what's going on.

**Comment by rocxa** [comment] 2020-06-15 18:35
I think it comes down to the directory, modules/contrib/civicrm instead of modules/civicrm or some of the other options that it probably accepts. I will test that theory.

**Comment by KarinG** [comment] 2020-06-15 18:40
Ok - > confirming that 
/modules/civicrm/ext/iatspayments is the ship with core location for Drupal 7.

**Comment by adixon** [comment] 2020-06-15 19:13
Just to clarify some erroneous bits above: files/civicrm is not a location that civicrm ships anything in --  that directory is created during the install and contains extensions you download. "shipping" means it's included in the files that are distributed as the civi package and it puts those in the ext directory of the modules directory (in your case, sites/[all or default]/modules/contrib/civicrm/ext).

Note that civicrm is finding a lot of files in your extension where it was shipped in, that is NOT the issue. The issue is that it is failing to find some files in the extension. What is not clear is, whether it is because of the location of those extension files, the point in the code that it's in, the case/naming, or something else, or due to some combination of those factors.

It does appear to be new to 5.26, but even that is not certain.

**Comment by KarinG** [comment] 2020-06-15 19:18
Alex is on 5.24.x

**Comment by rocxa** [comment] 2020-06-16 10:44
> Just to clarify some erroneous bits above: files/civicrm is not a location that civicrm ships anything in -- that directory is created during the install and contains extensions you download. "shipping" means it's included in the files that are distributed as the civi package and it puts those in the ext directory of the modules directory (in your case, sites/[all or default]/modules/contrib/civicrm/ext).
> 
> Note that civicrm is finding a lot of files in your extension where it was shipped in, that is NOT the issue. The issue is that it is failing to find SOME files in the extension. What is not clear is, whether it is because of the location of those extension files, the point in the code that it's in, the case/naming, or something else, or due to some combination of those factors.
> 
> It does appear to be new to 5.26, but even that is not certain.

The directory theory looks like a red herring as you say, we have some php overrides and it was muddying the waters in terms of the directory the error is reported in.  Removing the php overrides doesn't solve the problem.

I am still non the wiser on how to solve this problem.

**Comment by KarinG** [comment] 2020-06-16 12:26
@rocsa - what flavour of unix is your site on?

**Comment by rocxa** [comment] 2020-06-16 13:18
> @rocsa - what flavour of unix is your site on?

Apache/2.4.6 (Red Hat Enterprise Linux) PHP/7.3.17

**Comment by rocxa** [comment] 2020-06-16 15:22
I have now deleted the civicrm/ext/iatspayment that comes with the civicrm download from here/sourceforge  (https://civicrm.org/download)

and replaced it (in my custom extension directory) with the latest from here:
https://civicrm.org/extensions/iats-payments

it now appears to work.

So in short, the iATS extension included with core doesn't work.

**Comment by KarinG** [comment] 2020-06-16 15:46
Ok testing that theory now!
D7 / CiviCRM 5.24.6 -> iATS 1.7.2 -> the ships with core version:

Local path | /var/www/html/sites/all/modules/civicrm/ext/iatspayments

![image](https://user-images.githubusercontent.com/5340555/84794974-26e90180-afb4-11ea-9f71-c8dd86d8eff0.png)

![image](https://user-images.githubusercontent.com/5340555/84796386-cc50a500-afb5-11ea-92f2-029ca8c17b7c.png)

And that worked fine - a 1stPay Credit Card all the way through:
![image](https://user-images.githubusercontent.com/5340555/84795752-20a75500-afb5-11ea-91f7-3a83987fe888.png)

**Comment by rocxa** [comment] 2020-06-16 15:54
So it looks like it does work.. but there must be something about our specific config/server that stops it from that directory.

**Comment by KarinG** [comment] 2020-06-16 15:57
Let’s not close it yet. I want to run some more tests

**Comment by KarinG** [comment] 2020-06-16 17:04
Ok I ran some more tests - and all is well. Thanks for reporting it @rocxa - if there is anything else you run into - please do let us know 👍

**Closed by KarinG** 2020-06-16 17:04 UTC
