### ISSUE TITLE
One-Time Failed CC Contributions Created with Status of "Pending (Incomplete Transaction)" When Failed Message Returned from iATS

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#136] opened 2016-04-29 19:50 UTC
Copying from https://issues.civicrm.org/jira/browse/CRM-16417 per Alan's request:

**Alan Dixon added a comment - 29/Apr/16 5:32 PM**
I'm pretty sure this is all unrelated to the issue here and should probably be transferred to an iATS extension issue.

**Tamar Meir added a comment - 29/Apr/16 3:29 PM**
Hi Eileen and Alan,

The behavior we have observed pertains to one-time credit card transactions (_not _ event related) made from the back office - the contribution is created with a status of pending. A failed message is indeed received from the payment processor (iATS CC payments in this case which is why Alan chimed in) - I tested again through the iATS test processing account just to be sure (detailed steps at the bottom of this post) - the contribution remained in a status of pending. What I am not clear on is what is supposed to update the contribution to a status of failed - civi or the payment processor extension and what is the trigger for this update?

I am not a programmer (Alan loves it when I say that), but if I understand what you write in your post, the feature to reprocess a pending credit card contribution would need to be implemented by the payment processor extension, and it looks as if the code pertains only to event contributions, which would be enough if indeed all other non-event, on-time failed CC contributions were created with a status of failed, so further clarification to the above would be appreciated.

TESTING:

1. Create one-time credit card contribution for 0.01 cent using https://www.uk.iatspayments.com/NetGate/ProcessLink.asmx?WSDL (it's an Australian client)
2. Verified transaction communicated through to iATS (transaction ID: A26A02E, invoice ID: 7093526211e36b09e71c09cf2d5ee84c view-able on https://www.uk.iatspayments.com/Portal/Journal)
3. Verified response logged in civicrm_iats_response_log
4. Verified contribution status is "Pending (Incomplete Transaction)"

Thanks in advance for your patience and time in helping me figure this out,
Tamar

**Eileen McNaughton added a comment - 28/Apr/16 9:35 PM**
Are you saying that the contributions or the event registrations are not being updated to failed? The former should be updated to failed if the processor provides a failed result.

It is actually possible already to make a second credit card payment against a contribution - that has been a hidden feature for years although it's only been leveraged from one payment processor - which redirects to this url on a failed payment.

if ($component == "event")
{ $finalURL = CRM_Utils_System::url('civicrm/event/confirm', "reset=1&cc=fail&participantId=$privateData[participantID]", FALSE, NULL, FALSE ); }
I would probably prefer that the be the general use event-payment-fail url. But it would need testing /digging

**Tamar Meir added a comment - 28/Apr/16 3:54 PM**
Hi Alan,
This behavior also exhibits itself with back-end contributions, but it would be the front-end ones that would most likely slip under the users' radar - thanks for clarifying.
Tamar

**Alan Dixon added a comment -  28/Apr/16 1:53 PM**
Tamar: I believe this issue you are identifying is about the behaviour of the public ('front-end') contribution forms.

**Tamar Meir added a comment - 27/Apr/16 9:35 PM**
Hi Eileen,
My searching was unsuccessful in finding any open tickets in regards to failed credit card transactions being logged with a status of pending as of 4.7 - I have a couple questions regarding what you initially write:

"*The difficulty is what to do .... In theory this is an 'order' and a payment against it has failed (but the 'contribution-order' could still be paid in another way)."

I do not see any way of reprocessing a credit card contribution or recording a payment against the pending contribution that results from a failed CC transaction (such as with pay later and partially paid contributions) - are there plans to include this functionality in the near future? If not, my suggestion would be to mark the contribution as failed - this would save users the trouble of having to manually cancel pending contributions that may slip under their radar until they get used to this new behavior.

"This concept is mostly relevant to event registrations."
By this do you mean that this new behavior applies only to one-time credit card contributions, or would it also apply to subsequent installments of a recurring contribution?
Thanks in advance for your time in responding,
Tamar

**Comment by adixon** [comment] 2016-09-23 15:17
Tamar - can you still reproduce this?

**Comment by tamarmeir** [comment] 2016-09-23 15:45
Hi Alan,

So, this turned out to be a new behavior for all failed credit card transactions as of 4.7 - instead of not creating a contribution at all, a contribution with a status of pending is created - this isn't iATS specific so this issue should be closed her on GitHub, however, what is still missing is the ability to reprocess that pending transaction - the status can be changed or the entire contribution can be deleted, but changing the status to completed and including a transaction ID fails to create a financial transaction and that causes other issues (but this is a whole other can of worms that I will open on JIRA in my abundance of free time).

Eileen did mention this in her comment, the code of which I obviously don't have a clue what to do with: 

---EILEEN'S COMMENT START---

It is actually possible already to make a second credit card payment against a contribution - that has been a hidden feature for years although it's only been leveraged from one payment processor - which redirects to this url on a failed payment."

if ($component == "event")
{ $finalURL = CRM_Utils_System::url('civicrm/event/confirm', "reset=1&cc=fail&participantId=$privateData[participantID]", FALSE, NULL, FALSE ); }

I would probably prefer that the be the general use event-payment-fail url. But it would need testing /digging

---EILEEN'S COMMENT END---

Reminder - this issue is NOT just for event payments, but for all failed one-time credit card transactions for all payment processors as well as failed recurring contributions installments for iATS specifically, but I think that the bit of code that Eileen refers to needs to be implemented in Civi as opposed to a payment processor extension, correct?

Thanks for checking in on this!

**Comment by adixon** [comment] 2016-09-23 15:54
Okay, thanks for the clarification.

1. The bookkeeping issues. I believe that if you were to manually reprocess a payment, and then move the corresponding civi payment to complete and insert the transaction id, then the bookkeeping would now (as of 4.7.12) be correct. There's a relatively recent core patch from Karin that solved this. But yes, not an iATS issue.

2. Eileen's code looks like it's a way to generate a url where you can try a re-payment for an event participation when the initial one fails. There's nothing payment processor specific here, and I'm not sure it's dealing with any of the issues you've raised, though it's kind of cool. Also would be a new issue for core. Also I'm not clear whether there are analogous urls for eg. membership payment failures.

Closing.

**Closed by adixon** 2016-09-23 15:54 UTC
