### ISSUE TITLE
no line_items (contribution or financial) when using repeattransaction API (as of 4.7.9)

### ISSUE THREAD

**Issue by KarinG** [iATSPayments/com.iatspayments.civicrm#159] opened 2016-08-28 17:18 UTC
repeattransaction API may require original contribution ID in order to create the line_items + we still have to create line_items in 4.6 as well

**Comment by KarinG** [comment] 2016-08-28 18:09
Posted to chat.civicrm.org - I'm 99% sure that repeattransaction API was generating civicrm_line_item entries at some point. Though I could be mistaken. We can create these ourselves but the point it to use the CiviCRM APIs where we can.

**Comment by adixon** [comment] 2016-09-22 16:08
Seems to be working properly on your semper-it on 4.7.12, so I assume this is something you fixed in core?

**Comment by adixon** [comment] 2016-09-22 18:51
Confirmed that your core patch https://github.com/civicrm/civicrm-core/commit/17926a82b59aa0fc2080dd63c05d7efa3bcc6741 fixes line items.

**Closed by adixon** 2016-09-22 18:51 UTC
