### ISSUE TITLE
Financial Items Not Created for Subsequent Installments of Recurring Subscriptions (ACH & CC)

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#134] opened 2016-04-19 20:19 UTC
Hi Karin & Alan,

This issue, I believe, is closely related to closed issue #65 - after testing in an environment with Civi v. 4.7.6 and iATS master branch as of 3/1/2016, it seems that the issue still persists - no financial items are being created for subsequent installments of recurring contributions. This occurs only with payments processed via iATS (not Authorize.net or PayPal) and impacts both CC and ACH recurring contributions. Strangely enough, installments for recurring contributions that have a financial type with a sales tax account associated with it ARE creating financial items.

Please see attached file for more detail (although from an outdated version of civi and the extension, I believe it is still pertinent, but perhaps unnecessary as I believe you are familiar with this issue.
[financial_items_line_items_iATS.xlsx](https://github.com/iATSPayments/com.iatspayments.civicrm/files/226736/financial_items_line_items_iATS.xlsx)

For all subsequent installments of recurring subscriptions (regardless of sales tax account association), the `to_financial_account_id` in the civicrm_financial_trxn table reverts to the deposit bank account as opposed to the payment processing account with which the payment processor is configured (this last item might be a separate issue). 

Thanks in advance for your time on this issue,

Tamar

**Comment by KarinG** [comment] 2016-04-20 14:27
Hi Tamar!

Please note we're not supporting 4.7.x yet - there are still too many outstanding core/JIRA issues that prevent that. I'm having another go at 4.7/preliminary testing this week/next week - but must note that we don't create the financial line items - that should happen in core after a transaction is completed. iATS doesn't 'care' about your accounting. If there are new methods in 4.7 that we should be using to complete the transaction - we'll identify them - and then we can make edits on our end. But the fact that this is working with PayPal/Authorize.net ( IPN based processors ) is more likely due to assumptions than anything else. I'll keep this open to flag for my 4.7 testing. -- KarinG

**Comment by adixon** [comment] 2016-04-20 14:47
Ah, that's not exactly correct - we do create line items and try to follow the same path that other payment processors do (i.e. using the IPN code that generates matching line items), but it's not always successful, partly because there are some grey areas here (e.g. what to do if the amount of the recurring contribution changes). It's possible that changes in the 4.7 codebase require some updates to the code that's generating these contributions.

**Comment by KarinG** [comment] 2016-04-20 14:51
Thanks Alan - I'll keep an eye open for that when testing.

**Comment by tamarmeir** [comment] 2016-04-20 16:17
Thanks to both for your usual rapid responses - just to clarify - line items ARE being created in civicrm_line_item, but financial items are NOT being created in civicrm_financial_item when the financial type is NOT associated with a sales tax account. To replicate and verify the issues (CAPS used for clarification):


1. Create a sales tax financial account and associate it with a financial type http://docs.civicrm.org/user/en/4.6/contributions/sales-tax-and-vat/
2. Create two recurring contributions for two installments every 1 day (either ACH or CC - they are both impacted in the same manner), one with the financial type associated with the sales tax financial account, and one for a financial type that is NOT associated with the sales tax financial account
3. The initial contributions of each recurring subscription will look as expected in all of the relevant tables (line_item, entity_financial_item, financial_item, entity_financial_trxn, financial_trxn), but:

- The subsequent installment of the recurring contribution that is NOT associated with the sales tax financial account will NOT have a corresponding financial_item, although a financial_trxn is created and linked via the contribution_id
- The subsequent installment of the recurring contribution that IS associated with the sales tax financial account WILL have THREE corresponding financial_items INSTEAD OF TWO - one for the income account and one for the tax account, the third financial_item is recorded against the income account and ends up zeroing out the contribution - I have not been able to test for other payment processors, but this issue does not occur when creating cash/check contributions for financial types associated with sales tax accounts (this may be a separate issue in and of itself, and it is worth noting that the line item record for the recurring contribution is for the FULL amount of the contribution INCLUDING tax, where as the line item record for a cash/check contribution shows just the income amount LESS tax)
- Also, as stated in my first post, for all subsequent installments of recurring subscriptions (regardless of sales tax account association), the to_financial_account_id in the civicrm_financial_trxn table reverts to the deposit bank account as opposed to the payment processing account with which the payment processor is configured (this may also be a separate issue).

Thanks again for your time in looking into this and I am happy to help wherever I can,
Tamar

**Comment by adixon** [comment] 2016-04-20 16:26
Ah yes, I was confusing line items and financial items. This sounds like a lingering  issue with the IPN/api code that I'll have to review. Thanks for your detailed report!

I would assume that the tax stuff is triggering some extra code that rewrites the financial items, which is why it works differently.

**Comment by tamarmeir** [comment] 2016-05-23 17:32
Hi guys,

Not sure if this would substantiate a separate issue, but I am also noticing that subsequent installments of a recurring credit card subscription are being created with a payment instrument of check instead of credit card - this will wreak havoc on payment method reporting and accounting batch asset allocations - happy to show you an example of this at CiviCON, but wanted it to be on your radar.

Thanks,
Tamar

**Comment by tamarmeir** [comment] 2016-06-05 03:08
Hi guys,

Just an update - the issue with VAT is not payment processor specific, but I know that Karin and Eileen are working on the financial item issue which appears to be the result of IPN vs. API payment processing and perhaps something missing somewhere in an API that may be available in CORE for IPN processors.

**Comment by tamarmeir** [comment] 2016-07-26 19:22
Hi Karin,

Finally got around to testing today - took me much longer to document than I thought, but I was attempting to make the explanation as clear on paper as it would be if I were to explain the issue to you in person (or by screen share which we should probably try next time) - if I were to look at the attached file without any explanation, I think my eyeballs would pop out.

In essence, I am convinced I have reported 3 different issues in this one ticket, but I don't want to clog up your issue area so I will let you decide should you wish to split these issues out into separate tickets. The issues that still persist after testing are:

1. Subsequent installments of recurring contributions do not create necessary financial items - the issue does not appear to be fixed and it looks like the attempted fix added a new quirk - see attached file for details
2. Subsequent installments of recurring contributions do not preserve the original payment instrument ID 
3. Recurring contributions with financial types associated with sales tax financial accounts are not behaving as expected (again, this last issue isn't payment processor specific, but I think you would be a great help in communicating what may be wrong in CORE to Eileen with regards to this issue) - I couldn't complete testing of this last issue b/c of an issue with recurring payments scheduled job getting stuck - not sure if the attempted VAT contribution had anything to do with that or if that too should be considered a separate issue.

[
[iATS_master_civi_4.7.X_master_recurring.xlsx](https://github.com/iATSPayments/com.iatspayments.civicrm/files/384588/iATS_master_civi_4.7.X_master_recurring.xlsx)
](url)

Thanks in advance for your time!
Tamar

**Comment by allenthehusband** [comment] 2016-08-18 22:26
I am having the same issue as Tamar (#1 in her above comment) for subsequent recurring contributions, but I'm in Civi 4.6, using iATS extension 1.5.3.  Our completed subsequent recurring contributions are creating records in the civicrm_contribution, civicrm_entity_financial_trxn, civicrm_financial_trxn, and civicrm_line_item tables, but not in the civicrm_financial_item table.  What information can I provide to help?

I've cross posted on SE as well -- http://civicrm.stackexchange.com/q/14469/105.

**Comment by tamarmeir** [comment] 2016-08-19 00:10
I was wondering why I was the only complainer given that this issue surfaced with the advent of accounting batches. Karin made some headway a few weeks ago but it looks like Civi master branch didn't get along with it - Karin - any progress since? Not sure it's worth handling this conversation in tandem on stack exchange since it would be either Karin or Alan responsible for the fix.

**Comment by KarinG** [comment] 2016-09-06 03:26
He @tamarmeir - turns out it required a CiviCRM core fix - I dug in this weekend and we're now definitively creating financial_line_items for subsequent recurring contributions. I'll push all of the required code over to my live iats/demo site tomorrow - so that you can have a go at it.

**Comment by KarinG** [comment] 2016-09-06 03:27
Here's the PR: https://github.com/civicrm/civicrm-core/pull/8983 - but you can wait for me to merge it on my live iats/demo site.

**Comment by KarinG** [comment] 2016-09-19 17:21
Closing this - this is fixed as of 4.7.12 [Tamar confirmed "OK, tested and I believe we have success - a balanced IIF file is produced - yay!"] - and iATS master (working on getting an official 4.7 release out). See: https://issues.civicrm.org/jira/browse/CRM-19309 - and - https://github.com/civicrm/civicrm-core/pull/8983

**Closed by KarinG** 2016-09-19 17:21 UTC
