### ISSUE TITLE
Agreement never removed when using both Direct Debit (ACH) and Credit Card iATS processors on same page

### ISSUE THREAD

**Issue by JoeMurray** [iATSPayments/com.iatspayments.civicrm#34] opened 2014-09-12 01:34 UTC
See attached image.
![2014-09-11_21-30-29](https://cloud.githubusercontent.com/assets/300943/4244206/3bba1f30-3a1d-11e4-872b-f29837e22be1.png)

**Comment by tamarmeir** [comment] 2015-09-14 19:28
Hi Karin,

It's been a while since you last commented on this query - but the issue still prevails. As I am not a programmer, please forgive me if my question seems basic, but in reviewing the Main.tpl and Confirm.tpl files, it looks like there is "if" logic built in for both, but I noticed that when iATS ACH/EFT is marked as the default payment processor, then the agreement text appears no matter which payment processor option is selected. From what you write, I understand this to be an oversight by CiviCORE in one or both of the two files (Main.tpl and Confirm.tpl) - is that correct?

While the two files are easily edited, I assume that with each new version of Civi any edits will get wiped, so my preference would be for CiviCORE to add in the missing "if" when iATS ACH/EFT is set as the default, but I wanted to be sure that my logic is correct.

Thanks in advance for your time and your help!

**Comment by KarinG** [comment] 2015-09-17 20:35
As sorry - forgot to tag your post in my email. What CiviCRM are you using? What CMS? Let's figure out if this is still the case.

**Comment by tamarmeir** [comment] 2015-09-17 20:41
No worries, Karin. It's Civi 4.6.7 and Drupal 7.34.

Thanks!

**Comment by KarinG** [comment] 2015-09-17 20:51
And what iATS version?

**Comment by tamarmeir** [comment] 2015-09-17 20:52
Sorry to be piecemeal - 1.4

**Comment by KarinG** [comment] 2015-09-17 20:57
No worries. I will try reproduce it and get back to you.

**Comment by KarinG** [comment] 2015-09-23 17:12
So if the first time the form is loaded it contains a bank account number - then this message (below) is injected. I don't mean to be evasive - but this is not an iATS extension issue. It does not inject that message. If you can: make credit card default - and inject your own agreement message in one of the text boxes provided on the contribution page. 

{if $is_monetary and $form.bank_account_number}
  <div id="payment_notice">
    <fieldset class="crm-group payment_notice-group">
      <legend>{ts}Agreement{/ts}</legend>
      {ts}Your account data will be used to charge your bank account via direct debit. While submitting this form you agree to the charging of your bank account via direct debit.{/ts}
    </fieldset>
  </div>
  {/if}

**Closed by KarinG** 2015-09-23 17:12 UTC
