### ISSUE TITLE
Check Image & Account Type Missing in Online Contribution & Event Pages

### ISSUE THREAD

**Issue by tamarmeir** [iATSPayments/com.iatspayments.civicrm#164] opened 2016-09-22 19:46 UTC
CiviCRM 4.7.9, iATS 1.5.3

Hi Karin & Alan,

When creating ACH contributions via an online contribution or event page, the check image and account type field are missing - upon clicking "Continue", the system returns an error that the account type is a required field and both the check image and the account type field magically appear - the account type field is defaulted to "Checking", BTW, so not even sure why it is throwing this error.

Thanks in advance for your time looking into this issue,
Tamar

**Comment by adixon** [comment] 2016-09-22 20:05
Yes, this is a duplicate of an issue I've just closed, see:
https://github.com/iATSPayments/com.iatspayments.civicrm/issues/120

**Closed by adixon** 2016-09-22 20:05 UTC
