### ISSUE TITLE
the currency of a recurring-contribution is not regarded

### ISSUE THREAD

**Issue by thomst** [iATSPayments/com.iatspayments.civicrm#203] opened 2017-05-23 12:36 UTC
Creating a contribution from a recurring-contribution the code does not uses the currency of the recurring-contribution but the default currency. This breaks multi-currency-support.

**Comment by thomst** [comment] 2017-05-23 12:40
Actually we have a project where we need multi-currency-support. If this won't be fixed soon, I will do it myself. But I would be appriciative for any hint that eases the work with unknown code.

**Comment by adixon** [comment] 2017-05-23 15:40
Thanks for your report. In theory, I believe what you are describing should be supported and working in the extension code, but if you're using 4.7 and the currency is not being correctly set, then I suspect you are encountering a core bug.

Specifically: I think you are referring to the "process" link provided by the extension when looking at the recurring contribution record? i.e. what we call the 'card on file' functionality?

If that is what you are reporting about, then try it again without the "Create this as a contribution in the recurring series." option - I believe then it should correctly get the currency.

The currency is being set based on the contribution 'template', but if you use the default 'create the contribution in a recurring series', then the core 'repeattransaction' api is used, and that api may not handle the currency correctly yet.

The function _iats_process_contribution_payment in the iats.php file is responsible for creating the contribution record.

**Comment by adixon** [comment] 2017-05-23 15:53
Also, I should say that I've just tried to reproduce the error and wasn't able to, so perhaps CiviCRM core is functioning properly and I've just misunderstood the issue. Can you be sure to provide all relevant details, especially your CiviCRM and iATS extension versions?

**Comment by thomst** [comment] 2017-05-24 07:34
Thanks for your reply. So here are some details:
We are on CiviCRM 4.7.15 and use the current release of the extension 1.6.0. The system-default-currency is CHF.
What we did: We've created a recurring-contribution with an iATS-CreditCard-payment-processor and the currency USD. The first contribution was processed and set up directly with the right currency. But all following conrtibutions - processed by the iATS-scheduled-jobs - had the currency CHF instead of USD.

**Comment by KarinG** [comment] 2017-05-24 12:22
Thank you for the details - I'll try reproduce this with CAD and USD.

**Comment by adixon** [comment] 2017-05-24 19:05
Great, sounds like an important core issue. It might actually be fixed in the current release, there have been a number of currency-related issues + patches since 4.7.15.

**Comment by thomst** [comment] 2017-05-29 09:07
Ok. I have to get this running on a 4.7.15-environment.
Even if it is an issue of the civicrm-api there might be a way to address the api so that it respects the currency. In which way does the extensions api-calls create the contributions? Do they pass the currency?

**Comment by KarinG** [comment] 2017-05-29 14:40
Actually we use CiviCRM Core's repeattransaction API - if it's not repeating the transaction properly then we're looking at a CiviCRM Core bug. 

You can try the repeattransaction API on your site by going to:
civicrm/api#explorer
or: Support -> Developer -> API Explorer

```
    $result = civicrm_api3('Contribution', 'repeattransaction', array(
      'sequential' => 1,
      'contribution_status_id' => "",
    ));
```

I'm about to start more iATS testing and will look at this too.

**Comment by thomst** [comment] 2017-06-01 08:58
Thanks for the advice. Actually repeattransation fails to set the right currency in 4.7.15. I also couldn't find any jira-issue or change-log-entry that suggests this is fixed in later versions.

For now I just changed in iats.php:
`
 function _iats_civicrm_use_repeattransaction() {
  $version = CRM_Utils_System::version();
  return (version_compare($version, '4.7.12') < 0) ? FALSE : TRUE;
 }
`
into
`
 function _iats_civicrm_use_repeattransaction() {
  return FALSE;
 }
`
This fixes the issue with the currency. But fails to set the correct payment-instrument-id. It just uses the default one...

**Comment by KarinG** [comment] 2017-06-03 04:44
Thank you for alerting us to a serious issue in repeatransaction API - I've reproduced it and have filed a ticket w/ CiviCRM Core: https://issues.civicrm.org/jira/browse/CRM-20678;

As you've noticed your workaround will work to get the currency right - but completetransaction API does not get all the bookkeeping entries correct - that's why we're now making use of repeattransaction API - which is the recommended API for generating subsequent contributions in a recurring series in CiviCRM; I'm sure it will get some attention soon - as it's not just us using this API.

**Comment by KarinG** [comment] 2017-06-03 04:45
Closing this - please follow progress on this issue on CiviCRM Core's JIRA: https://issues.civicrm.org/jira/browse/CRM-20678

**Closed by KarinG** 2017-06-03 04:45 UTC

**Comment by KarinG** [comment] 2017-06-12 01:04
Hey @thomst - one of our partners in Australia has put together a fix for this issue: https://github.com/civicrm/civicrm-core/pull/10490 - are you in a position to QA/try the proposed fix?
